### ISSUE TITLE
errCallBack Is not defined.

### ISSUE THREAD

**Issue by littleman10** [raulrene/Twitter-ContestJS-bot#10]
@raulrene After about 10 mins of it running it stops, with a big error message that starts with "errCallBack Is not defined" I believe this is because it tried to retweet something that it has already retweets, which breaks it, and then I have to manually restart it which is not ideal as I would like to leave this running all the time without having to worry about it, anyway to fix this?

**Comment by raulrene** [comment]
Hi @littleman10 , there are a lot of open issues at this point because this was implemented in a 2-hour run for fun and I don't really have the time to maintain it right now. Hopefully I'll get some time in the following days to take a look over some of the issues. In the meanwhile, if you can reproduce in a more specific way, let me know because that would help. I haven't encountered your problem so far.

**Comment by littleman10** [comment]
This is a screenshot of the problem, however where it says "User is over daily update status limit" that is because I have used to so much today, it would normally say "You have already re-tweeted this tweet" or "you have been blocked from retweeting this account at the request of the user". Thanks a lot for trying to help :)
Date: Sat, 5 Dec 2015 14:02:38 -0800

**Comment by henhouse** [comment]
Here's a screenshot from my end. 
![j8ozmps](https://cloud.githubusercontent.com/assets/30731/11733553/915b897c-9f7c-11e5-8ef9-0ac4757e64eb.png)

**Comment by Zen00** [comment]
Yeah, I didn't run into that error, but I didn't have full logging on which is what I think you're doing.

**Comment by littleman10** [comment]
@Zen00 What is full logging? And should I not have it on?

**Comment by Shyzer** [comment]
I'm getting the same error as Henhouse after running the script for a few minutes. It'll RT a good 20 or 30 tweets then end up spitting out that error.
