### ISSUE TITLE
The program stops after a while

### ISSUE THREAD

**Issue by himat** [raulrene/Twitter-ContestJS-bot#12]
Can you make it so that the program just waits but keeps running so I don't have to keep restarting it every time it stops?

**Comment by ps6000** [comment]
I have been trying to figure out a way to do this. I have been running the bot through forever, which will run it as a system service. You can monitor the bot running, but I have not figure out how to get it to restart.

My problem is the twitter daily(hourly etc) limit, that forces the script to quit. I am thinking that I can restart it twice a day and have it rt the max allowed.

**Comment by himat** [comment]
What exactly causes the script to quit? Doesn't it just end when the searchResultsArr is empty?
So if it's empty, can't you just make the script wait for an hour or so and then call the search and retween functions again?

**Comment by ps6000** [comment]
Yes, I think you could just continuously call the script. I am having trouble automating that portion myself. As I said I am using forever to run it as a system service but am having trouble getting it running as a cron job.

I think using the task scheduler in the OS is the best way to get the script to run over and over again instead of building that functionality into the script. Take a look at running it with forever and/or with a cron task and let me know if you get anywhere with it.

**Comment by ps6000** [comment]
I have it working now with forever and crontab. What was jamming me up was cron doesn't have the env variables set so you have to run them in the script. The following will run the script on the hour. I seem to be getting about 200 retweets an hour using this method. This may be a little hacky so if anyone reading this has a better idea I am all ears!

I run the script with forever to have it run as a system service so that I don't need to keep a shell up. So all I need to do is call forever restartall to restart the script. 

Created a script called twrestarter, which contains the restart command, then make it executable
  
    export NODE_ENV=production
        export PATH=/usr/local/bin:$PATH
        forever restartall

Then I add this line with crontab -e to call the script which calls the script.
    0 * * * * cd /root && ./twrestarter

The only problem I see is that this method will not survive a reboot, need to think about that one.

**Comment by himat** [comment]
Oh that's actually a good idea to use the OS. I've done this sort of thing before on Windows but I didn't think of it for this.
But it seems to be working and is a lot simpler than what you're doing, but you're using Linux so I guess this wouldn't work for you.
I'm using Windows Task Scheduler to automatically run the index.js file every hour (I'll probably make the interval smaller), and it's working great.

**Comment by ps6000** [comment]
I think it's always best to isolate some layers from the app. Windows task scheduler should work fine for this. Although you may want to look into having it run as a system service I think its still running as a user right now.
