### ISSUE TITLE
Not Filtering Retweets

### ISSUE THREAD

**Issue by Zen00** [raulrene/Twitter-ContestJS-bot#2]
Doesn't seem to be filtering retweets from the to be tweeted results. Again, I'm new and don't know yet why. :(

**Comment by Zen00** [comment]
After looking at the issue a bit more, it seems that it's not filtering out retweets that people do of embedded tweets from other sites.

**Comment by Zen00** [comment]
So the one site will have a tweet like "Do X and X to win!", then the person will click the retweet button which will cause it to retweet with a link to the tweet embedded in their tweet, and a copy of the tweet text, which confuses the search function.

**Comment by raulrene** [comment]
Hi @Zen00 

I encountered this but as far as I know it's fixed. I'm not sure exactly why it's not working for you. Maybe can you link me to some tweets so that I try to manually run them through the Twitter Bot to see if they go or not?

Initially it wasn't filtering out retweets, but I added to the search query to find only tweets that are not RT. This is the search query

    retweet to win -vote -filter:retweets OR RT to win -vote -filter:retweets

Based on the [API Specifications](https://dev.twitter.com/rest/public/search) this should find all tweets containing the words "retweet to win", that *don't* containt the word "vote", and it filters out retweets. Alternatively, it searches for the words "RT to win", filters out the word "vote" and filters out retweets.

Based on how much I tried the API it worked fine for me. As I've said, maybe give me some clear examples of when it fails (s.a. a link to a RT that should not be retweeted, but it does anyway). Maybe I can re-write the query somehow.

**Comment by Zen00** [comment]
Okay so here's a screenshot of the 3 most common types of "Bad Retweets" that happen. http://snag.gy/jc1dF.jpg

The -filter filter works just fine for removing normal retweeting, but as you can see in the screenshot there are 3 types of retweets that do not get filtered out.

The first (at the bottom) is one where someone (in this case AverageJIM65) tweets out a @person followed by the retweeted message.

The second (in the middle) is when someone goes to a website and clicks on a button on that site to retweet an embedded tweet (I believe), this creates a double.

The third (at the top) is similar to the first, except without the @ mention.

**Comment by raulrene** [comment]
Hm, interesting cases.

I think the only one we can work with is the first you mentioned, with the @person. We can filter out tweets that start with mentioning a user. However, I'm afraid that cases such as the second and third are not filterable, because I can't find any good pattern for them. 

Do you have any proposals?

**Comment by Zen00** [comment]
I wish I could find one, but after searching through the Twitter API documentation I couldn't find anything about them.

At least removing the @ replies would be good. I can block users who retweet the other type and eventually I'll clean up all the bots.

However, I don't know if it's possible, but can you filter by HTML? If you can, then you could filter out any tweets that contain the "QuoteTweet-link" class. That would work.

**Comment by Zen00** [comment]
Got a reply on Stackoverflow.

"There's no API parameter which will exclude this.  include_rts=false only applies to regular retweets, not quoted Tweets.

What you can do is manually filter them out.

If you look at the API response, you'll see something like this for embedded Tweets:

"quoted_status_id": 661258770480132100,
"quoted_status_id_str": "661258770480132096",
"quoted_status": {
  "created_at": "Mon Nov 02 19:09:11 +0000 2015",
  "id": 661258770480132100,
  "id_str": "661258770480132096",
So, if a Tweet has a quoted_status_id have your code skip over it."

**Comment by nivong** [comment]
filter:retweets is not active anymore.

**Comment by Shyzer** [comment]
Thanks for that followup, Zen. Would anybody know how to include this script to filter out any tweets with the "quoted_status_id" tag?

**Comment by raulrene** [comment]
@Shyzer I can add an enhancement task for that

**Comment by raulrene** [comment]
https://github.com/raulrene/Twitter-ContestJS-bot/issues/21
