### ISSUE TITLE
Why doesn't it retweet everything corresponding to the searchQueries?

### ISSUE THREAD

**Issue by xem** [raulrene/Twitter-ContestJS-bot#20]
Hello,

I've used your bot for the last couple days and noticed it only retweetd and followed a few dozens contest tweets a day.

If I do a manual search like https://twitter.com/search?q=rt%20win&src=typd
I find hundreds of contests that my bot hasn't retweeted and that are much more interesting than the ones it has retweeted.

Do you know why? and how to fix that?

Thanks!

**Comment by raulrene** [comment]
Probably because you only searched for "rt win". 

There are multiple parameters used now by the bot, mainly because it was spamming too much. We've filtered out retweets for starters. Secondly, it dismisses tweets that contain the word "vote". Third, it looks for both popular tweets and recent ones.

Also, as an improvement by someone in the community who used the app, there is a parameter for "minimum retweets needed by a tweet" in order for us to care about it (currently 10). This significantly reduces the amount of fake contests retweeted and stops retweeting other bots that retweet retweets of other bots.

Another aspect is the max. tweets the original poster has. If it has more than 20000, it's likely to be a bot so we dismiss it.

There are all configurable, though, You will find them at the top of the index.js file as constants, so you can play around with them to change outcomes of the bot.
